param(
    [string]$InputPath = "src/main/resources/styles/screens.css",
    [string]$OutputPath = "src/main/resources/styles/screens.css"
)

$ErrorActionPreference = "Stop"
$source = Get-Content -LiteralPath $InputPath -Raw -Encoding UTF8
$source = [regex]::Replace($source, '/\*[\s\S]*?\*/', '')
$blocks = [regex]::Matches($source, '(?s)([^{}]+)\{([^{}]*)\}')
$rules = @{}
$index = 0
foreach ($block in $blocks) {
    $selector = ([regex]::Replace($block.Groups[1].Value, '\s+', ' ')).Trim()
    if ([string]::IsNullOrWhiteSpace($selector) -or $selector.StartsWith('@')) { continue }
    if (-not $rules.ContainsKey($selector)) {
        $rules[$selector] = [ordered]@{ Properties = [ordered]@{}; Last = 0 }
    }
    foreach ($declaration in $block.Groups[2].Value -split ';') {
        $colon = $declaration.IndexOf(':')
        if ($colon -lt 1) { continue }
        $property = $declaration.Substring(0, $colon).Trim()
        $value = $declaration.Substring($colon + 1).Trim()
        if ($property -and $value) { $rules[$selector].Properties[$property] = $value }
    }
    $rules[$selector].Last = $index++
}

$palette = [ordered]@{
    '#060c09'='-fc-bg-0'; '#050b08'='-fc-bg-0'; '#030806'='-fc-bg-0';
    '#07110d'='-fc-bg-1'; '#08120d'='-fc-bg-1'; '#09150f'='-fc-bg-1';
    '#0a1710'='-fc-bg-2'; '#0a1911'='-fc-bg-2'; '#0a1912'='-fc-bg-2';
    '#0b1812'='-fc-bg-2'; '#0c1a12'='-fc-bg-2'; '#0d1c14'='-fc-bg-2';
    '#10251a'='-fc-bg-3'; '#10231a'='-fc-bg-3'; '#123b27'='-fc-burgundy-soft';
    '#1d633b'='-fc-burgundy'; '#31e981'='-fc-coral'; '#2ce77b'='-fc-coral';
    '#24db72'='-fc-coral'; '#46f493'='-fc-coral-hover'; '#28e57f'='-fc-coral';
    '#28533a'='-fc-line'; '#244a34'='-fc-line'; '#1b3d2a'='-fc-line';
    '#173624'='-fc-line'; '#cfe5d6'='-fc-text-soft'; '#bde8cc'='-fc-text-soft';
    '#e8f7ed'='-fc-text'; '#effff4'='-fc-text'; '#83a28e'='-fc-text-muted'
}

$header = "/* Generated by scripts/consolidate-ui-css.ps1. Edit source components, then regenerate. */`r`n"
$output = [System.Text.StringBuilder]::new($header)
foreach ($entry in $rules.GetEnumerator() | Sort-Object { $_.Value.Last }) {
    [void]$output.AppendLine("$($entry.Key) {")
    foreach ($property in $entry.Value.Properties.GetEnumerator()) {
        $value = $property.Value
        foreach ($replacement in $palette.GetEnumerator()) {
            $value = $value.Replace($replacement.Key, $replacement.Value)
        }
        [void]$output.AppendLine("    $($property.Key): $value;")
    }
    [void]$output.AppendLine("}")
}
[IO.File]::WriteAllText((Resolve-Path (Split-Path $OutputPath)).Path + '\' +
        (Split-Path $OutputPath -Leaf), $output.ToString(), [Text.UTF8Encoding]::new($false))

"INPUT_RULES=$($blocks.Count) OUTPUT_RULES=$($rules.Count) OUTPUT=$OutputPath"
